apiVersion: v1
kind: Service
metadata:
  labels:
    module: {{ $.Chart.Name }}
  name: {{ $.Chart.Name }}-service
  namespace: {{ .Values.nginx.params.namespace }}
spec:
  type: ClusterIP
  selector:
    module: {{ $.Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376