{{- range .Values.global.nginxReplicaGroups }}
apiVersion: v1
kind: Service
metadata:
  labels:
    module: {{ $.Chart.Name }}
    nginxGroup: {{ $.Chart.Name }}-{{ .name }}
  name: {{ $.Chart.Name }}-service-{{ .name }}
  namespace: {{ .namespace }}
spec:
  type: ClusterIP
  selector:
    nginxGroup: {{ $.Chart.Name }}-{{ .name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
{{- end }}