---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-operator
  labels:
    app: addon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addon-operator
  template:
    metadata:
      labels:
        app: addon-operator
    spec:
      containers:
      - name: addon-operator
        image: localhost:5000/addon-operator-poc:latest
        imagePullPolicy: Always
        env:
        - name: DYNAMIC_CONFIGMAP_NAME
          value: dynamic-test
        - name: ADDON_OPERATOR_PROMETHEUS_METRICS_PREFIX
          value: dev_cluster_
        - name: ADDON_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOG_LEVEL
          value: debug
        - name: VALUES_JSON_PATCH_PATH
          value: /tmp/module-runtime-patch.json
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9650
      serviceAccountName: addon-operator-acc